"""Add vehicle specifications

Revision ID: 488222ee3c67
Revises: a89dcd3ca76a
Create Date: 2025-02-23 00:44:56.537835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488222ee3c67'
down_revision = 'a89dcd3ca76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('engine_type', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('horsepower', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('torque', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('max_towing', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('drivetrain', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('transmission', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_capacity', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_economy_city', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_economy_hwy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'fuel_economy_hwy')
    op.drop_column('vehicles', 'fuel_economy_city')
    op.drop_column('vehicles', 'fuel_capacity')
    op.drop_column('vehicles', 'transmission')
    op.drop_column('vehicles', 'drivetrain')
    op.drop_column('vehicles', 'max_towing')
    op.drop_column('vehicles', 'torque')
    op.drop_column('vehicles', 'horsepower')
    op.drop_column('vehicles', 'engine_type')
    # ### end Alembic commands ###
