# This is a template to show required secrets
# DO NOT ADD ACTUAL SECRETS HERE - Use GitHub Repository Settings

name: Required Secrets Template

on:
  workflow_dispatch:  # Manual trigger only for documentation

jobs:
  document-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: List Required Secrets
        run: |
          echo "The following secrets need to be configured in GitHub Repository Settings:"
          echo ""
          echo "VIN_API_KEY:"
          echo "  Description: API key for vehicle information lookups"
          echo "  Example format: abc123def456..."
          echo ""
          echo "AWS_ACCESS_KEY_ID:"
          echo "  Description: AWS access key for deployments"
          echo "  Example format: AKIA..."
          echo ""
          echo "AWS_SECRET_ACCESS_KEY:"
          echo "  Description: AWS secret key for deployments"
          echo "  Example format: abc123def456..."
          echo ""
          echo "ECR_REGISTRY:"
          echo "  Description: Amazon ECR registry URL"
          echo "  Example format: 123456789012.dkr.ecr.region.amazonaws.com"
          echo ""
          echo "SLACK_WEBHOOK_URL:"
          echo "  Description: Slack webhook for deployment notifications"
          echo "  Example format: https://hooks.slack.com/services/..." 